name: CI Workflow

env:
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  REGION: ${{ secrets.REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest --cov=app --cov-report=html
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        run: |
          COMMIT_ID=${GITHUB_SHA::7}
          docker build -t flask-boilerplate .
          docker tag flask-boilerplate flask-boilerplate:${COMMIT_ID}
          docker image ls
      - name: Push image to ECR
        run: |
          aws configure set aws_access_key_id $ACCESS_KEY_ID
          aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
          aws configure set region $REGION
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO
          COMMIT_ID=${GITHUB_SHA::7}
          docker tag flask-boilerplate:${COMMIT_ID} $ECR_REPO/flask-boilerplate:${COMMIT_ID}
          docker tag flask-boilerplate $ECR_REPO/flask-boilerplate:latest
          docker push $ECR_REPO/flask-boilerplate:${COMMIT_ID}
          docker push $ECR_REPO/flask-boilerplate:latest
      
      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster flask-cluster --service flask-service --force-new-deployment
          echo "Deployment to ECS initiated"
          
      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Deployment completed successfully"
          else
            echo "Deployment failed"
          fi