name: CI Workflow

env:
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  REGION: ${{ secrets.REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest --cov=app --cov-report=html
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        run: |
          COMMIT_ID=${GITHUB_SHA::7}
          docker build -t flask-boilerplate .
          docker tag flask-boilerplate flask-boilerplate:${COMMIT_ID}
          docker image ls
      - name: Push image to ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO
          docker push flask-boilerplate:${COMMIT_ID} $ECR_REPO